<?php

define('DEV_MODE', true);

defined('CLIENT_JS_VERSION') || define('CLIENT_JS_VERSION', OXSAR_VERSION.CLIENT_VERSION);
defined('CLIENT_CSS_VERSION') || define('CLIENT_CSS_VERSION', OXSAR_VERSION.CLIENT_VERSION);
defined('CLIENT_SOUNDS_VERSION') || define('CLIENT_SOUNDS_VERSION', OXSAR_VERSION.CLIENT_VERSION);
defined('CLIENT_IMAGES_VERSION') || define('CLIENT_IMAGES_VERSION', OXSAR_VERSION.CLIENT_VERSION);

$GLOBALS["ADMIN_USERS"] = array(
    1, // craft
);

define('UNIVERSE_NAME', 'Dominator');

// define('OBSERVER_OFF_CREDIT_COST', 10);

define('NUM_GALAXYS', 3); // sync with na_galaxy_new_active
define('NUM_SYSTEMS', 300); // sync with na_system_new_active
// planets - na_planet_new_active

define("MAX_PLANETS", 12);
define("ADDITIONAL_ARTEFACT_PLANETS_NUMBER", 5);
define("TEMP_PLANETS_NUMBER", 5);

define('SHOW_USER_AGREEMENT', true);
define('SHOW_DM_POINTS', true);
define('ACHIEVEMENTS_ENABLED', false);
define('TUTORIAL_ENABLED', false);

define('BLOCK_TARGET_BY_ALLY_ATTACK_USED_PERIOD', 60*60*24*1);

define('BASHING_PERIOD', 60*60*5);
define('BASHING_MAX_ATTACKS', 4);

define('NEW_USER_OBSERVER', 0);
define('PROTECTION_PERIOD', 60*60*24);

define("EXCH_INVIOLABLE", 0);

define("EXCH_NEW_PROFIT_TYPE", true);

define("EXCH_MERCHANT_PREMIUM_COMMISSION", 10);
define("EXCH_MERCHANT_COMMISSION", 13);

define("EXCH_NO_MERCHANT_PREMIUM_COMMISSION", 16);
define("EXCH_NO_MERCHANT_COMMISSION", 19);

define('UNITS_GROUP_CONSUMTION_POWER_BASE', 1.000004);

define("RES_TO_UNIT_POINTS", (1.0 / 1000) * 2.0);
define("RES_TO_RESEARCH_POINTS", (1.0 / 1000) * 1.0 * 0.5);
define("RES_TO_BUILD_POINTS", (1.0 / 1000) * 0.5 * 0.1);

$GLOBALS["INITIAL_BUILDINGS"] = array(
    UNIT_METALMINE => 2,
    UNIT_SILICON_LAB => 2,
    UNIT_HYDROGEN_LAB => 2,
    UNIT_SOLAR_PLANT => 4,
    UNIT_ROBOTIC_FACTORY => 2,
    UNIT_SHIPYARD => 2,
    UNIT_RESEARCH_LAB => 2,
    UNIT_DEFENSE_FACTORY => 1,
    UNIT_REPAIR_FACTORY => 1,
);

$GLOBALS["INITIAL_RESEARCHES"] = array(
    UNIT_COMPUTER_TECH => 1,
    UNIT_ENERGY_TECH => 1,
    UNIT_COMBUSTION_ENGINE => 2,

);

$GLOBALS["INITIAL_UNITS"] = array(
    UNIT_SMALL_TRANSPORTER => 20,
    // UNIT_LARGE_TRANSPORTER => 10,
    UNIT_LIGHT_FIGHTER => 10,
    // UNIT_STRONG_FIGHTER => 5,
    UNIT_RECYCLER => 10,
    UNIT_COLONY_SHIP => 3,
    UNIT_ESPIONAGE_SENSOR => 10,
);

define('GAMESPEED_SCALE', 8);
define('GAMESPEED', 0.75 / GAMESPEED_SCALE);

define('FLY_SPEED_SCALE', 1);
define('ROCKET_SPEED_FACTOR', GAMESPEED_SCALE * FLY_SPEED_SCALE);

for($i = 1; $i <= NUM_GALAXYS; $i++){
    $GLOBALS["GALAXY_SPEC_PARAMS"][$i] = array(
        "ADVANCED_BATTLE" => 0,
        "PLANET_CONSTRUCTION_SPEED_FACTOR" => 1,
        "MOON_CONSTRUCTION_SPEED_FACTOR" => 2,
        "TEMP_MOON_CONSTRUCTION_SPEED_FACTOR" => 4,
        "FLEET_BUILDING_SPEED_FACTOR" => 1,
        "DEFENSE_BUILDING_SPEED_FACTOR" => 1,
        "RESEARCH_SPEED_FACTOR" => 2,
        "RESOURCES_PRODUCTION_FACTOR" => 5,
        "ENEGRY_PRODUCTION_FACTOR" => 0.8,
        "STORAGE_FACTOR" => 5,
        "FLEET_SPEED_FACTOR" => FLY_SPEED_SCALE,
        "ALLOW_DESTROY_BUILDING" => 0,
        "ALLOW_DESTROY_MOON" => 1,
        "ALLOW_STARGATE_TRANSPORT" => 1,
    );
}
