<?php

// define('BASHING_PERIOD', 60*60*24);
// define('BASHING_MAX_ATTACKS', 5);

define('SHOW_PLEASE_ACTIVATE_ACCOUNT', true);

define('PROTECTION_PERIOD', 60*60*24);

define("EXCH_MERCHANT_PREMIUM_COMMISSION", 10);
define("EXCH_MERCHANT_COMMISSION", 13);

define("EXCH_NO_MERCHANT_PREMIUM_COMMISSION", 16);
define("EXCH_NO_MERCHANT_COMMISSION", 19);
