artefacts:
  artefact_300:
    id: 300
    buyable: true
    movable: true
    usable: true
    trophy_chance: 5
    use_times: 1
    use_duration: 604800
    lifetime: 2592000
    effect_type: 1
    max_active: 1
    quota: 0.3
  artefact_301:
    id: 301
    buyable: true
    movable: true
    usable: true
    trophy_chance: 5
    use_times: 1
    use_duration: 604800
    lifetime: 2592000
    effect_type: 1
    max_active: 5
    quota: 0.2
  artefact_302:
    id: 302
    buyable: true
    movable: true
    usable: true
    trophy_chance: 5
    use_times: 1
    use_duration: 604800
    lifetime: 2592000
    effect_type: 1
    max_active: 5
    quota: 0.3
  artefact_303:
    id: 303
    buyable: true
    movable: true
    usable: true
    trophy_chance: 5
    use_times: 1
    use_duration: 604800
    lifetime: 2592000
    effect_type: 1
    max_active: 5
    quota: 0.1
  artefact_304:
    id: 304
    buyable: true
    movable: true
    trophy_chance: 20
    delay: 3600
    use_times: 10
    lifetime: 2592000
    effect_type: 2
    quota: 0.3
  artefact_305:
    id: 305
    buyable: true
    movable: true
    usable: true
    trophy_chance: 20
    delay: 3600
    use_times: 2
    use_duration: 259200
    lifetime: 2592000
    effect_type: 1
    max_active: 2
    quota: 0.08
  artefact_315:
    id: 315
    buyable: true
    movable: true
    usable: true
    trophy_chance: 20
    delay: 3600
    use_times: 2
    use_duration: 604800
    lifetime: 2592000
    effect_type: 0
    max_active: 2
    quota: 0.1
  artefact_316:
    id: 316
    buyable: true
    movable: true
    trophy_chance: 20
    delay: 3600
    use_times: 5
    lifetime: 2592000
    effect_type: 3
    quota: 0.1
  artefact_317:
    id: 317
    buyable: true
    movable: true
    trophy_chance: 20
    delay: 3600
    use_times: 5
    lifetime: 2592000
    effect_type: 3
    quota: 0.1
  artefact_318:
    id: 318
    buyable: true
    movable: true
    trophy_chance: 20
    delay: 3600
    use_times: 5
    lifetime: 2592000
    effect_type: 3
    quota: 0.1
  artefact_319:
    id: 319
    buyable: true
    movable: true
    usable: true
    trophy_chance: 0
    use_times: 1
    lifetime: 5184000
    effect_type: 0
    quota: 0.01
  artefact_320:
    id: 320
    buyable: true
    movable: true
    trophy_chance: 0
    use_times: 1
    lifetime: 5184000
    effect_type: 4
    quota: 0.005
  artefact_321:
    id: 321
    buyable: true
    movable: true
    usable: true
    trophy_chance: 1
    use_times: 1
    lifetime: 2592000
    effect_type: 0
    quota: 0.01
  artefact_322:
    id: 322
    buyable: true
    movable: true
    usable: true
    trophy_chance: 1
    use_times: 1
    lifetime: 2592000
    effect_type: 1
    quota: 0.01
  artefact_323:
    id: 323
    buyable: true
    movable: true
    trophy_chance: 1
    use_times: 1
    lifetime: 2592000
    effect_type: 0
    quota: 0.05
  artefact_324:
    id: 324
    buyable: true
    movable: true
    trophy_chance: 1
    use_times: 1
    lifetime: 2592000
    effect_type: 1
    quota: 0.05
